// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: template/proto/query.proto

package com.json_push.protobuf;

public final class QueryProtobuf {
  private QueryProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ParamValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:template.proto.ParamValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string value = 1;</code>
     */
    java.util.List<java.lang.String>
        getValueList();
    /**
     * <code>repeated string value = 1;</code>
     */
    int getValueCount();
    /**
     * <code>repeated string value = 1;</code>
     */
    java.lang.String getValue(int index);
    /**
     * <code>repeated string value = 1;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes(int index);
  }
  /**
   * Protobuf type {@code template.proto.ParamValue}
   */
  public  static final class ParamValue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:template.proto.ParamValue)
      ParamValueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ParamValue.newBuilder() to construct.
    private ParamValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParamValue() {
      value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ParamValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                value_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              value_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          value_ = value_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.json_push.protobuf.QueryProtobuf.internal_static_template_proto_ParamValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.json_push.protobuf.QueryProtobuf.internal_static_template_proto_ParamValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.json_push.protobuf.QueryProtobuf.ParamValue.class, com.json_push.protobuf.QueryProtobuf.ParamValue.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList value_;
    /**
     * <code>repeated string value = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getValueList() {
      return value_;
    }
    /**
     * <code>repeated string value = 1;</code>
     */
    public int getValueCount() {
      return value_.size();
    }
    /**
     * <code>repeated string value = 1;</code>
     */
    public java.lang.String getValue(int index) {
      return value_.get(index);
    }
    /**
     * <code>repeated string value = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes(int index) {
      return value_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < value_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < value_.size(); i++) {
          dataSize += computeStringSizeNoTag(value_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getValueList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.json_push.protobuf.QueryProtobuf.ParamValue)) {
        return super.equals(obj);
      }
      com.json_push.protobuf.QueryProtobuf.ParamValue other = (com.json_push.protobuf.QueryProtobuf.ParamValue) obj;

      boolean result = true;
      result = result && getValueList()
          .equals(other.getValueList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getValueCount() > 0) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValueList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.json_push.protobuf.QueryProtobuf.ParamValue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.json_push.protobuf.QueryProtobuf.ParamValue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.json_push.protobuf.QueryProtobuf.ParamValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.json_push.protobuf.QueryProtobuf.ParamValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.json_push.protobuf.QueryProtobuf.ParamValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.json_push.protobuf.QueryProtobuf.ParamValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.json_push.protobuf.QueryProtobuf.ParamValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.json_push.protobuf.QueryProtobuf.ParamValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.json_push.protobuf.QueryProtobuf.ParamValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.json_push.protobuf.QueryProtobuf.ParamValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.json_push.protobuf.QueryProtobuf.ParamValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.json_push.protobuf.QueryProtobuf.ParamValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.json_push.protobuf.QueryProtobuf.ParamValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code template.proto.ParamValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:template.proto.ParamValue)
        com.json_push.protobuf.QueryProtobuf.ParamValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.json_push.protobuf.QueryProtobuf.internal_static_template_proto_ParamValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.json_push.protobuf.QueryProtobuf.internal_static_template_proto_ParamValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.json_push.protobuf.QueryProtobuf.ParamValue.class, com.json_push.protobuf.QueryProtobuf.ParamValue.Builder.class);
      }

      // Construct using com.json_push.protobuf.QueryProtobuf.ParamValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.json_push.protobuf.QueryProtobuf.internal_static_template_proto_ParamValue_descriptor;
      }

      public com.json_push.protobuf.QueryProtobuf.ParamValue getDefaultInstanceForType() {
        return com.json_push.protobuf.QueryProtobuf.ParamValue.getDefaultInstance();
      }

      public com.json_push.protobuf.QueryProtobuf.ParamValue build() {
        com.json_push.protobuf.QueryProtobuf.ParamValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.json_push.protobuf.QueryProtobuf.ParamValue buildPartial() {
        com.json_push.protobuf.QueryProtobuf.ParamValue result = new com.json_push.protobuf.QueryProtobuf.ParamValue(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          value_ = value_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.json_push.protobuf.QueryProtobuf.ParamValue) {
          return mergeFrom((com.json_push.protobuf.QueryProtobuf.ParamValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.json_push.protobuf.QueryProtobuf.ParamValue other) {
        if (other == com.json_push.protobuf.QueryProtobuf.ParamValue.getDefaultInstance()) return this;
        if (!other.value_.isEmpty()) {
          if (value_.isEmpty()) {
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureValueIsMutable();
            value_.addAll(other.value_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.json_push.protobuf.QueryProtobuf.ParamValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.json_push.protobuf.QueryProtobuf.ParamValue) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValueIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          value_ = new com.google.protobuf.LazyStringArrayList(value_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getValueList() {
        return value_.getUnmodifiableView();
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public int getValueCount() {
        return value_.size();
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public java.lang.String getValue(int index) {
        return value_.get(index);
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes(int index) {
        return value_.getByteString(index);
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public Builder setValue(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
        value_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public Builder addValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
        value_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public Builder addAllValue(
          java.lang.Iterable<java.lang.String> values) {
        ensureValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, value_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public Builder clearValue() {
        value_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string value = 1;</code>
       */
      public Builder addValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureValueIsMutable();
        value_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:template.proto.ParamValue)
    }

    // @@protoc_insertion_point(class_scope:template.proto.ParamValue)
    private static final com.json_push.protobuf.QueryProtobuf.ParamValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.json_push.protobuf.QueryProtobuf.ParamValue();
    }

    public static com.json_push.protobuf.QueryProtobuf.ParamValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParamValue>
        PARSER = new com.google.protobuf.AbstractParser<ParamValue>() {
      public ParamValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ParamValue(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ParamValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParamValue> getParserForType() {
      return PARSER;
    }

    public com.json_push.protobuf.QueryProtobuf.ParamValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:template.proto.Query)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
     */
    int getQueryParamsCount();
    /**
     * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
     */
    boolean containsQueryParams(
        java.lang.String key);
    /**
     * Use {@link #getQueryParamsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue>
    getQueryParams();
    /**
     * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
     */
    java.util.Map<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue>
    getQueryParamsMap();
    /**
     * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
     */

    com.json_push.protobuf.QueryProtobuf.ParamValue getQueryParamsOrDefault(
        java.lang.String key,
        com.json_push.protobuf.QueryProtobuf.ParamValue defaultValue);
    /**
     * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
     */

    com.json_push.protobuf.QueryProtobuf.ParamValue getQueryParamsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code template.proto.Query}
   */
  public  static final class Query extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:template.proto.Query)
      QueryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Query.newBuilder() to construct.
    private Query(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Query() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Query(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                queryParams_ = com.google.protobuf.MapField.newMapField(
                    QueryParamsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue>
              queryParams__ = input.readMessage(
                  QueryParamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              queryParams_.getMutableMap().put(
                  queryParams__.getKey(), queryParams__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.json_push.protobuf.QueryProtobuf.internal_static_template_proto_Query_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetQueryParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.json_push.protobuf.QueryProtobuf.internal_static_template_proto_Query_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.json_push.protobuf.QueryProtobuf.Query.class, com.json_push.protobuf.QueryProtobuf.Query.Builder.class);
    }

    public static final int QUERYPARAMS_FIELD_NUMBER = 1;
    private static final class QueryParamsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue>newDefaultInstance(
                  com.json_push.protobuf.QueryProtobuf.internal_static_template_proto_Query_QueryParamsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.json_push.protobuf.QueryProtobuf.ParamValue.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue> queryParams_;
    private com.google.protobuf.MapField<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue>
    internalGetQueryParams() {
      if (queryParams_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            QueryParamsDefaultEntryHolder.defaultEntry);
      }
      return queryParams_;
    }

    public int getQueryParamsCount() {
      return internalGetQueryParams().getMap().size();
    }
    /**
     * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
     */

    public boolean containsQueryParams(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetQueryParams().getMap().containsKey(key);
    }
    /**
     * Use {@link #getQueryParamsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue> getQueryParams() {
      return getQueryParamsMap();
    }
    /**
     * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
     */

    public java.util.Map<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue> getQueryParamsMap() {
      return internalGetQueryParams().getMap();
    }
    /**
     * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
     */

    public com.json_push.protobuf.QueryProtobuf.ParamValue getQueryParamsOrDefault(
        java.lang.String key,
        com.json_push.protobuf.QueryProtobuf.ParamValue defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue> map =
          internalGetQueryParams().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
     */

    public com.json_push.protobuf.QueryProtobuf.ParamValue getQueryParamsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue> map =
          internalGetQueryParams().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetQueryParams(),
          QueryParamsDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue> entry
           : internalGetQueryParams().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue>
        queryParams__ = QueryParamsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, queryParams__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.json_push.protobuf.QueryProtobuf.Query)) {
        return super.equals(obj);
      }
      com.json_push.protobuf.QueryProtobuf.Query other = (com.json_push.protobuf.QueryProtobuf.Query) obj;

      boolean result = true;
      result = result && internalGetQueryParams().equals(
          other.internalGetQueryParams());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetQueryParams().getMap().isEmpty()) {
        hash = (37 * hash) + QUERYPARAMS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetQueryParams().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.json_push.protobuf.QueryProtobuf.Query parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.json_push.protobuf.QueryProtobuf.Query parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.json_push.protobuf.QueryProtobuf.Query parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.json_push.protobuf.QueryProtobuf.Query parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.json_push.protobuf.QueryProtobuf.Query parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.json_push.protobuf.QueryProtobuf.Query parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.json_push.protobuf.QueryProtobuf.Query parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.json_push.protobuf.QueryProtobuf.Query parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.json_push.protobuf.QueryProtobuf.Query parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.json_push.protobuf.QueryProtobuf.Query parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.json_push.protobuf.QueryProtobuf.Query parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.json_push.protobuf.QueryProtobuf.Query parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.json_push.protobuf.QueryProtobuf.Query prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code template.proto.Query}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:template.proto.Query)
        com.json_push.protobuf.QueryProtobuf.QueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.json_push.protobuf.QueryProtobuf.internal_static_template_proto_Query_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetQueryParams();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableQueryParams();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.json_push.protobuf.QueryProtobuf.internal_static_template_proto_Query_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.json_push.protobuf.QueryProtobuf.Query.class, com.json_push.protobuf.QueryProtobuf.Query.Builder.class);
      }

      // Construct using com.json_push.protobuf.QueryProtobuf.Query.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableQueryParams().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.json_push.protobuf.QueryProtobuf.internal_static_template_proto_Query_descriptor;
      }

      public com.json_push.protobuf.QueryProtobuf.Query getDefaultInstanceForType() {
        return com.json_push.protobuf.QueryProtobuf.Query.getDefaultInstance();
      }

      public com.json_push.protobuf.QueryProtobuf.Query build() {
        com.json_push.protobuf.QueryProtobuf.Query result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.json_push.protobuf.QueryProtobuf.Query buildPartial() {
        com.json_push.protobuf.QueryProtobuf.Query result = new com.json_push.protobuf.QueryProtobuf.Query(this);
        int from_bitField0_ = bitField0_;
        result.queryParams_ = internalGetQueryParams();
        result.queryParams_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.json_push.protobuf.QueryProtobuf.Query) {
          return mergeFrom((com.json_push.protobuf.QueryProtobuf.Query)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.json_push.protobuf.QueryProtobuf.Query other) {
        if (other == com.json_push.protobuf.QueryProtobuf.Query.getDefaultInstance()) return this;
        internalGetMutableQueryParams().mergeFrom(
            other.internalGetQueryParams());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.json_push.protobuf.QueryProtobuf.Query parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.json_push.protobuf.QueryProtobuf.Query) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue> queryParams_;
      private com.google.protobuf.MapField<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue>
      internalGetQueryParams() {
        if (queryParams_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              QueryParamsDefaultEntryHolder.defaultEntry);
        }
        return queryParams_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue>
      internalGetMutableQueryParams() {
        onChanged();;
        if (queryParams_ == null) {
          queryParams_ = com.google.protobuf.MapField.newMapField(
              QueryParamsDefaultEntryHolder.defaultEntry);
        }
        if (!queryParams_.isMutable()) {
          queryParams_ = queryParams_.copy();
        }
        return queryParams_;
      }

      public int getQueryParamsCount() {
        return internalGetQueryParams().getMap().size();
      }
      /**
       * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
       */

      public boolean containsQueryParams(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetQueryParams().getMap().containsKey(key);
      }
      /**
       * Use {@link #getQueryParamsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue> getQueryParams() {
        return getQueryParamsMap();
      }
      /**
       * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
       */

      public java.util.Map<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue> getQueryParamsMap() {
        return internalGetQueryParams().getMap();
      }
      /**
       * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
       */

      public com.json_push.protobuf.QueryProtobuf.ParamValue getQueryParamsOrDefault(
          java.lang.String key,
          com.json_push.protobuf.QueryProtobuf.ParamValue defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue> map =
            internalGetQueryParams().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
       */

      public com.json_push.protobuf.QueryProtobuf.ParamValue getQueryParamsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue> map =
            internalGetQueryParams().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearQueryParams() {
        internalGetMutableQueryParams().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
       */

      public Builder removeQueryParams(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableQueryParams().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue>
      getMutableQueryParams() {
        return internalGetMutableQueryParams().getMutableMap();
      }
      /**
       * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
       */
      public Builder putQueryParams(
          java.lang.String key,
          com.json_push.protobuf.QueryProtobuf.ParamValue value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableQueryParams().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .template.proto.ParamValue&gt; queryParams = 1;</code>
       */

      public Builder putAllQueryParams(
          java.util.Map<java.lang.String, com.json_push.protobuf.QueryProtobuf.ParamValue> values) {
        internalGetMutableQueryParams().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:template.proto.Query)
    }

    // @@protoc_insertion_point(class_scope:template.proto.Query)
    private static final com.json_push.protobuf.QueryProtobuf.Query DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.json_push.protobuf.QueryProtobuf.Query();
    }

    public static com.json_push.protobuf.QueryProtobuf.Query getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Query>
        PARSER = new com.google.protobuf.AbstractParser<Query>() {
      public Query parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Query(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Query> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Query> getParserForType() {
      return PARSER;
    }

    public com.json_push.protobuf.QueryProtobuf.Query getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_template_proto_ParamValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_template_proto_ParamValue_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_template_proto_Query_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_template_proto_Query_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_template_proto_Query_QueryParamsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_template_proto_Query_QueryParamsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032template/proto/query.proto\022\016template.p" +
      "roto\"\033\n\nParamValue\022\r\n\005value\030\001 \003(\t\"\224\001\n\005Qu" +
      "ery\022;\n\013queryParams\030\001 \003(\0132&.template.prot" +
      "o.Query.QueryParamsEntry\032N\n\020QueryParamsE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(\0132\032.templ" +
      "ate.proto.ParamValue:\0028\001B\'\n\026com.json_pus" +
      "h.protobufB\rQueryProtobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_template_proto_ParamValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_template_proto_ParamValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_template_proto_ParamValue_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_template_proto_Query_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_template_proto_Query_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_template_proto_Query_descriptor,
        new java.lang.String[] { "QueryParams", });
    internal_static_template_proto_Query_QueryParamsEntry_descriptor =
      internal_static_template_proto_Query_descriptor.getNestedTypes().get(0);
    internal_static_template_proto_Query_QueryParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_template_proto_Query_QueryParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
